### PR TITLE
Upgrade mongoose version to 5.9.6

### PR DESCRIPTION
**Pull request by qwu16**

### CODE REVIEW

**Review by jhou5 — APPROVED** [review]

**Comment by jhou5** [comment]
@qwu16 can we change to directly use docker containers simply using: FROM openvisualcloud/xeon-ubuntu1804-service-owt, easy to maintain as one OVC and save Video Conferencing Sample build time.

**Comment by qwu16** [comment]
> @qwu16 can we change to directly use docker containers simply using: FROM openvisualcloud/xeon-ubuntu1804-service-owt, easy to maintain as one OVC and save Video Conferencing Sample build time.

Video conferencing Sample and Dockerfiles are 2 different repos, can we assume that all the users who clone video conferencing sample have already cloned Dockerfiles repo? If yes, then i think we can change it. Video conference sample Dockerfile is based on Dockerfile in Dockerfiles repo and only add one startup script.

**Comment by jhou5** [comment]
* they don't need to clone Dockerfiles repo, they would directly pull images from dockerhub: https://hub.docker.com/r/openvisualcloud/xeon-ubuntu1804-service-owt, 

* as you mentioned, "Video conference sample Dockerfile is based on Dockerfile in Dockerfiles repo and only add one startup script.", then it would be much more easier and make sense to use dockerhub image, an example is smart city: https://github.com/OpenVisualCloud/Smart-City-Sample/blob/master/analytics/common/Xeon/gst/Dockerfile

* I can help if you want.

**Comment by qwu16** [comment]
> * they don't need to clone Dockerfiles repo, they would directly pull images from dockerhub: https://hub.docker.com/r/openvisualcloud/xeon-ubuntu1804-service-owt,
> * as you mentioned, "Video conference sample Dockerfile is based on Dockerfile in Dockerfiles repo and only add one startup script.", then it would be much more easier and make sense to use dockerhub image, an example is smart city: https://github.com/OpenVisualCloud/Smart-City-Sample/blob/master/analytics/common/Xeon/gst/Dockerfile
> * I can help if you want.

That would be much easier if we can pull image from dockerhub, i don't know that before, i will update the Dockerfile and directly use dockerhub image. Thanks for the information.

**Comment by jhou5** [comment]
@qwu16 Sure, feel free to let me konow if you need help.

**Pull request merged**
